### ISSUE TITLE
What is the reason for "still fetching soundfont" error?

### ISSUE THREAD

**Issue by trosel** [oakes/ansiwave#10]
https://github.com/ansiwave/ansiwave/blob/add5977d9327299c9e5bb5f90fd7ba5820b73bdf/src/ansiwavepkg/midi.nim#L52

I was trying to see if people that didn't have an ansiwave account could click the link and hear my song anyway. What I noticed is that I get this error when I try to click play. How do I fix this?

Note: I'm using the web app and trying to link others to my song via the web link

**Comment by trosel** [comment]
Ah! I figured out that it just takes a while to load the module. I suppose the request is to maybe have some kind of notification for when a song will be able to play

**Comment by oakes** [comment]
Yeah i need to show a progress bar when you get that error, so you know when the soundfont is ready. Should be pretty easy; i'll update this issue when that's done.

**Comment by oakes** [comment]
OK i updated it to say "fetching soundfont..." and then it automatically starts playing once it has downloaded. It doesn't show progress right now but it's at least better than making the user try again on their own :D
