### ISSUE TITLE
debian 10 GLIBC_2.29 not found 

### ISSUE THREAD

**Issue by v1nc** [oakes/ansiwave#4]
Running the prebuild binary on a fresh debian-10 returns
`/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./ansiwave)`

**Comment by oakes** [comment]
Please try downloading it now and running it again. I rebuilt it with static linking so hopefully it will work better now:

https://github.com/oakes/ansiwave/releases/download/0.3.0-linux/ansiwave

**Comment by v1nc** [comment]
that was fast, works fine now :smiling_face_with_three_hearts:
