### ISSUE TITLE
Unable to paste from system clipboard on web-version

### ISSUE THREAD

**Issue by machocam** [oakes/ansiwave#9]
Currently I am unable to paste from my clipboard into the editor in the web-version. Is this by design?

**Comment by oakes** [comment]
It's a limitation but i plan on fixing it soon. The editor is custom built so it doesn't have some built-in features like copy/paste, but i think it should be possible to add via contenteditable. I'll update this issue once i figure out a solution.

**Comment by oakes** [comment]
This is now fixed in the web client's editor. Please try it out when you get the chance.
